### ISSUE TITLE
Matlab2017 not support .lib files

### ISSUE THREAD

**Issue by ZQInQAAS** [marianux/ecg-kit#13]
Hello, sorry to bother you .I met a question when using LIBRA/adjustedboxplot.m
My matlab version(R2017b) does not support mcc.lib function
It only has "loadlibrary" function but need  .h files
Could you give me a mcc.m/mcc.h or tell me how to solve this problem?
Thanks a lot!
（I‘m a Chinese graduate student,I find this adjustedboxplot algorithm in a literature`A novel system for automatic removal of ocular artefacts in EEG by using outlier detection methods and ICA `.I'm working on electroencephalogram progressing.  Looking forward to your reply. Thanks again.)

**Comment by marianux** [comment]
LIBRA is a satellite project that I use in the toolbox, go to them in order to get support. I dont know what you are talking about, all that we use from LIBRA is included in the repository.

Best,
M.
