### ISSUE TITLE
old p code

### ISSUE THREAD

**Issue by atpage** [marianux/ecg-kit#6]
When running `first_simple_example.m` I get the following error:

> `The P-code file <...>/common/prtools_addins/private/covm.p was generated prior to MATLAB version 7.5 (R2007b) and is no longer supported.  Use pcode to regenerate the file using MATLAB R2007b or later.`

This is in MATLAB 2015b.  I suspect the same issue will occur with other p files in the project as well.

**Comment by marianux** [comment]
Hi atpage, thanks for the feedback !

I run the same example in r2015a without problem. I will move this to the forum and try to provide more details about your system and what where and when the problem occurs.

Kind regards,
M.

**Comment by marianux** [comment]
Sorry I mean, ask this in the forum at 

http://marianux.github.io/ecg-kit/

and lets try to solve this.

M.

**Comment by atpage** [comment]
Hi Mariano,
It seems pretty straightforward: http://www.mathworks.com/help/matlab/ref/pcode.html

> If your P-file was generated prior to MATLAB 7.5, it will not run in MATLAB 8.6 (Release R2015b) or later.

So you're just one update away from it happening to you!  It looks like you simply have to re-run `pcode(function)` in a newer copy of MATLAB to generate an updated p file.  Unfortunately, we (users) can't, because we don't have the original code.

Alex

**Comment by marianux** [comment]
Alex, PRtools is a sepparate toolbox that I don't administer and therefore,
I can't recompile. You can download PRtools by yourself and replace by the
one included in ecg-kit/common folder. Keep me updated if this corrects the
problem, since I can not replicate this problem in r2015a.

Best,
M.

**Comment by atpage** [comment]
Great, thanks for the tip!  I was able to download PRTools from their website, and have recompiled the .p files using their source code.  Pull request is here: https://github.com/marianux/ecg-kit/pull/7 .  Note that the .p files actually aren't even required now, because the .m files are complete, but you may still want them for performance reasons.
