### ISSUE TITLE
To Test Sensitivity of your P wave Detection?

### ISSUE THREAD

**Issue by sami10007** [marianux/ecg-kit#9]
Dear Sir, 

I would like to test minimally PR interval detection for HRV metrics with your package and understand why still RR intervals are used much for HRV metrics. You have something about P wave detection in `pwavef.m`. I would love to understand better how sensitive your `pwavef.m`, `pwavedet.c` and `pwave_task1.m` can be with basic time/frequency analysis too besides your wavelet analysis. The latter `pwave_task1.m` seems to be for the detection task. Do you have any studies just about it with HRV metrics? 

My interpretation of the codes
- p wave detection - `pwavef.m`, `pwavedet.c` and `pwave_task1.m`
- wavelet analysis - `wavedet`, `PlotWaveMarks` and `ecgkit_wave_defs`
- some grouping - `groupnlineup_waves` 
- some plotting for general trends apparently - `PlotGlobalWaveMarks`  

I think I would simply use MIT-BIH arrythmia database but I am also welcome to other proposals. Any starter about code/example where to start to edit is more than welcome!

Best regards, 
Sami

**Comment by marianux** [comment]
Hi Sami, please ask this question in the forum. I will answer there.

http://marianux.github.io/ecg-kit/

Best,
M.
